# Generated by Django 3.0.7 on 2020-06-25 18:12

import builtins
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('date_sorted', models.DateField(default=datetime.datetime(2020, 6, 25, 18, 12, 27, 528552), verbose_name='Fecha de registro')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/% Y/% m/% d/')),
                ('c_vitae', models.ImageField(blank=True, null=True, upload_to='c_vitae/% Y/% m/% d/')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': [builtins.id],
            },
        ),
    ]
